apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ${PVC_NAME}  # triton-models
  namespace: ${NAMESPACE}  # default
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: ${STORAGE_SIZE}  # 1200Gi
  storageClassName: ""
  volumeMode: Filesystem
  volumeName: ${PV_NAME}  # pv-triton-models
